require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'vendor/bundle/**/*'

AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Layout/LineLength:
  Max: 120

Lint/UselessAssignment:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/InverseOf:
  Enabled: false
