version: '3'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    command: foreman start
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:password@mysql:3306
    volumes:
      - .:/app_name
      - public-data:/roomer/public
      - tmp-data:/roomer/tmp
      - log-data:/roomer/log
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
      MYSQL_USERNAME: root
    ports:
    - 4306:3306
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - public-data:/roomer/public
      - tmp-data:/roomer/tmp
volumes:
  public-data:
  tmp-data:
  log-data:
  mysql_data: